baseURL = 'https://data-viz-lectures.com/'
languageCode = 'ja'
title = 'データ可視化講習'
theme = 'stack'
defaultContentLanguage = 'ja'


enableRobotsTXT = true

[minify]
    disableXML = true
    minifyOutput = true

[pagination]
pagerSize = 10

[params]
description = '本講習は、マーケティング、セールスなどのビジネスパーソンや、デザイナー、エンジニアなどのクリエイター、企業経営者、コンサルタント、行政関係者、議会議員など、データ活用に関わる全ての職業の方を対象にしています。'
mainSections = ['posts']
featuredImageField = 'image'
lightMode = 'auto'

    [params.defaultImage.opengraph]
        enabled = true
        local = false
        src = "/images/avatar.png"

    [params.opengraph.twitter]
        site = "visualizing_jp"
        card = "summary"

[params.dateFormat]
published = "2006年01月02日"
lastUpdated = "2006年01月02日"

[params.sidebar]
emoji = '📊'
subtitle = ''
compact = false

[params.sidebar.author]
    name = "矢崎裕一／Yuichi Yazaki"
    image = "/images/avatar.png"
    bio = "株式会社ビジネス・アーキテクツにてユーザー・インターフェイス・デザイナーおよびアート・ディレクターを7年間経験後、独立。企業や教育機関での講義活動、ウェブサイトVisualizing.JPにおける情報発信、コミュニティData Visualization Japanにおけるコミュニティ活動など、データ可視化の実践と普及に関するさまざまな活動をおこなっている。共著書に『RESASの教科書』(日経BP、2016)がある。千葉工業大学デザイン科学修士修了。データ・ビジュアライゼーション・ジャパン発起人/Yahoo!ニュース・エキスパート。"

[params.sidebar.avatar]
    enabled = true
    local = false
    src = "/images/avatar.png"

[params.widgets]
    [[params.widgets.homepage]]
        type = "archives"

    [[params.widgets.homepage]]
        type = "categories"

    [[params.widgets.homepage]]
        type = "tag-cloud"
    
    [[params.widgets.page]]
        type = "toc"

[menus]
  [[menus.main]]
  name = 'ホーム'
  pageRef = '/'
  weight = 1
  [[menus.main]]
  name = '講習'
  pageRef = '/categories/course'
  weight = 10

  [[menus.main]]
  name = 'パーソナルトレーニング'
  url = 'https://personal.data-viz-lectures.com/'
  weight = 20

  [[menus.main]]
  name = '講演・研修'
  url = 'https://data-viz-lectures.com/posts/keynote-training/'
  weight = 40
  [[menus.main]]
  name = 'オンデマンド動画'
  url = 'https://data-viz-lectures.com/posts/udemy-data-cleaning/'
  weight = 50
  [[menus.main]]
  name = '受講者の声'
  pageRef = '/categories/testimonials'
  weight = 60
  [[menus.main]]
  name = '運営者について'
  pageRef = '/categories/about'
  weight = 100
  [[menus.main]]
  name = 'お問い合わせ'
  pageRef = '/pages/contact'
  weight = 200

  [[menus.main]]
  name = '利用規約'
  pageRef = '/pages/terms-of-service'
  weight = 203

  [[menus.main]]
  name = 'プライバシーポリシー'
  pageRef = '/pages/privacy-policy'
  weight = 205

  [[menus.main]]
  name = '特定商取引法に基づく表記'
  pageRef = '/pages/legal'
  weight = 210
